import { useEffect, useState } from 'react';
import { api } from '../api/client';

const FALLBACK_DISCLAIMER =
  'RESEARCH SIGNALS ONLY -- not investment advice, not a guaranteed outcome. ' +
  'Outputs are generated by an automated research tool and must be independently ' +
  'verified before any capital is risked.';

/** The one persistent disclaimer footer, present on every screen -- never a
 * per-screen warning block. Text is fetched from /api/meta so it can never
 * drift from claudetrade.version.DISCLAIMER; a static fallback keeps the
 * footer from ever rendering empty before that request resolves. */
export function Footer() {
  const [text, setText] = useState(FALLBACK_DISCLAIMER);
  const [version, setVersion] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    api
      .meta()
      .then((meta) => {
        if (!cancelled) {
          setText(meta.disclaimer);
          setVersion(meta.code_version);
        }
      })
      .catch(() => {
        /* keep the fallback text -- the footer must never depend on the API */
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <footer className="shrink-0 border-t border-gridline bg-page px-4 py-2 text-[11px] leading-snug text-ink-muted">
      <span>{text}</span>
      {version && <span className="ml-2 text-ink-muted/70">v{version}</span>}
    </footer>
  );
}
