"""Regenerate src/claudetrade/sentiment/common_words.py.

Run manually (dev-only; wordfreq is NOT a runtime dependency):

    pip install wordfreq && python scripts/generate_common_words.py

The output module is committed so the application never needs wordfreq at
runtime. Regenerate only if the collision set needs refreshing.
"""

from __future__ import annotations

from pathlib import Path

from wordfreq import top_n_list

#: Internet/trading shorthand that a frequency wordlist misses but that
#: floods finance forums. Curated by hand; keep sorted.
ACRONYMS = sorted(
    {
        "AF", "AH", "ATH", "ATL", "BTFD", "CEO", "CFO", "COO", "CPI", "DCA",
        "DD", "EOD", "EOW", "EOY", "EPS", "ETA", "ETF", "EV", "FD", "FDS",
        "FOMO", "FUD", "FY", "FYI", "GDP", "GG", "GL", "HODL", "IIRC", "IMHO",
        "IMO", "IPO", "IRA", "IRS", "ITM", "IV", "LFG", "LMAO", "LOL", "MC",
        "MM", "NGL", "OG", "OP", "OTM", "PE", "PPS", "PSA", "PT", "QQQ",
        "ROI", "RSI", "SEC", "SMH", "TA", "TBH", "TIA", "TLDR", "TOS", "USD",
        "WSB", "YOLO", "YTD",
    }
)

def main() -> None:
    words = top_n_list("en", 30000)
    short = sorted({w.upper() for w in words if 1 <= len(w) <= 8 and w.isalpha() and w.isascii()})
    out = Path(__file__).resolve().parents[1] / "src/claudetrade/sentiment/common_words.py"
    with out.open("w", encoding="utf-8") as f:
        f.write('"""GENERATED by scripts/generate_common_words.py -- do not edit by hand.\n\n')
        f.write("Uppercase 1-8 letter tokens that are common English/internet words\n")
        f.write("(wordfreq top-30k, a corpus that includes Reddit) plus curated\n")
        f.write("finance/internet acronyms. Any universe symbol colliding with one of\n")
        f.write("these must take the ambiguous-mention path in entity resolution: a\n")
        f.write('bare "IMO" is almost never Imperial Oil, and a bare "DD" is almost\n')
        f.write("never DuPont. Cashtags, company names, and finance context still\n")
        f.write("resolve such symbols confidently -- this list discounts, never blocks.\n")
        f.write('"""\n\nfrom __future__ import annotations\n\n')
        f.write("COMMON_WORDS_AND_ACRONYMS: frozenset[str] = frozenset({\n")
        for w in sorted(set(short) | set(ACRONYMS)):
            f.write(f'    "{w}",\n')
        f.write("})\n")
    print(f"wrote {out} ({len(set(short) | set(ACRONYMS))} entries)")

if __name__ == "__main__":
    main()
