"""Version and build identity.

``CODE_VERSION`` is stamped onto every signal, backtest run and audit record so
that a stored result can be traced back to the code that produced it.  When the
package is running from a git checkout we append the short commit hash; when it
is running from a PyInstaller bundle we fall back to the packaged version only.
"""

from __future__ import annotations

import subprocess
from functools import lru_cache
from pathlib import Path

__version__ = "0.1.0"

DISCLAIMER = (
    "RESEARCH SIGNALS ONLY -- not investment advice, not a guaranteed outcome. "
    "Outputs are generated by an automated research tool and must be independently "
    "verified before any capital is risked."
)


@lru_cache(maxsize=1)
def _git_revision() -> str | None:
    """Return the short git SHA of the working tree, or ``None`` when unavailable."""
    repo_root = Path(__file__).resolve().parents[2]
    if not (repo_root / ".git").exists():
        return None
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    sha = out.stdout.strip()
    return sha or None


@lru_cache(maxsize=1)
def code_version() -> str:
    """Full code identity string, e.g. ``0.1.0+g1a2b3c4d5e6f``."""
    sha = _git_revision()
    return f"{__version__}+g{sha}" if sha else __version__


CODE_VERSION: str = code_version()
